languageCode = "en"
languageName = "English"
weight = 1
title = "Mitja Martini"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/mitja-avatar.png"  # removed to show only name in header
  description = "Mitja Martini's blog about AI Engineering"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Mitja Martini"
  image = "img/mitja-avatar.png"
  headline = ""
  bio = ""
   links = [
     #{ link = "https://nunocoracao.github.io/blowfish/" },
     { github = "https://github.com/mitja" },
     { x-twitter = "https://twitter.com/MitjaMartini" }
   ]
