languageCode = "de"
languageName = "Deutsch"
weight = 2
title = "Mitja Martini"

[params]
  displayName = "DE"
  isoCode = "de"
  rtl = false
  logo = "img/mitja-avatar.png"
  description = "Mitja Martinis Blog Ã¼ber AI Engineering"
  dateFormat = "2. January 2006"

[params.author]
  name = "Mitja Martini"
  image = "img/mitjamartini.jpg"
  headline = "IT Solution Designer, AI Engineer"
  bio = "IT Solution Designer und AI Engineer"
   links = [
     { github = "https://github.com/mitja" },
     { x-twitter = "https://twitter.com/MitjaMartini" }
   ]
