# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "AI Engineering"
#  pageRef = "ai-engineer"
#  weight = 5

[[main]]
  name = "Beiträge"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "Kategorien"
  pageRef = "categories"
  weight = 25

#[[main]]
#  identifier = "appointment"
#  name = "Termin buchen"
#  #pre = "bell"
#  url = "https://nunocoracao.github.io/blowfish/"
#  weight = 30

#[[main]]
#  identifier = "phone"
#  pre = "phone"
#  url = "https://nunocoracao.github.io/blowfish/"
#  weight = 40

[[main]]
  identifier = "mail"
  pre = "email"
  url = "mailto:hi@mitjamartini.com"
  weight = 50

#[[main]]
#  identifier = "github"
#  pre = "github"
#  url = "https://github.com/nunocoracao/blowfish"
#  weight = 50

#[[main]]
#  identifier = "twitter"
#  pre = "twitter"
#  url = "https://twitter.com/burufugu"
#  weight = 60


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


 [[footer]]
   name = "Über mich"
   pageRef = "about"
   weight = 10

# [[footer]]
#   name = "Geschäftsbedingungen"
#   pageRef = "terms"
#   weight = 20

 [[footer]]
   name = "Datenschutz"
   pageRef = "privacy"
   weight = 30