# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "cupcake-forest" # blowfish, marvel
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]
# robots = ""

[header]
  layout = "basic" # valid options: basic, fixed

[footer]
 # showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" #"background" #"profile" # valid options: page, profile, hero, card, background (default), custom
  homepageImage = "img/oberbaum-bridge-view.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 7
  showMoreLink = true
  showMoreLinkDest = "posts"
  streamView = false # show full content for posts with stream: true in front matter
  streamItems = 10 # number of posts to scan for stream (full content) posts
  streamSections = ["posts"] # sections to include in the stream
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = true
  #showViews = true
  #showLikes = true
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background (default)
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true 
  showAuthorsBadges = false 
  showWordCount = true
  showSummary = true
  sharingLinks = [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email"]

[list]
  showHero = false
  heroStyle = "background" # valid options: basic, big, background (default)
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = false
  #showTaxonomies = true # not working
  showCards = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = true

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true

[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
